version: "3.9"

networks:
  inv_net:
    external: true
    name: inv_net

services:
  nginx:
    image: nginx:1.27-alpine
    container_name: landingInvernaderos
    restart: unless-stopped
    networks:
      - inv_net
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8080/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
